import sys
import os 
import pandas as pd
import pandas_ta as ta
from sqlalchemy.ext.asyncio import async_sessionmaker
from sqlalchemy.dialects.postgresql import insert

sys.path.append(os.path.dirname(os.dirname(os.path.abspath(__file__))))

from backend.db.connection import engine

SessionLocal = async_sessionmaker(engine, expire_on_commit=False)

async def compute_signal(symbol: str):
    """fetch prices, compute signals via pandas_ta, and upsert to database"""
    async with SessionLocal() as session:
        #1. fetch prices from db
        stmt = select(Prices).where(Price.symbol == symbol).order_by(Price.data.asc())
        result = await session.execute(stmt)
        prices = result.scalars().all()

        if not prices:
            print(f"No prices found for {symbil}")
            return 
        
        #2. Convert to Dataframe
        data = [{
            "date": p.date,
            "cose": float(p.adj_close) if p.adj_close is not None else float(p.close)
        } for p in prices]

        df = pd.DataFrame(data)
        df.set_index("date", inplace=True)

        #3. Compute Signals
        # Daily Return percentage
        df['daily_return'] = df['close'].pct_change() * 100
        # 7-day Return percentage
        df['return_7d'] = df['close'].pct_change(periods=7) * 100
        # Simple Moving Averages
        df['sma_20'] = ta.sma(df['close'], length=20)
        df['sma_50'] = ta.sma(df['close'], length=50)
        # RSI
        df['rsi_14'] = ta.rsi(df['close'], length=14)
        # volatility (Rolling standard deviation of return annualized)
        df['volatility_20d'] = df['daily_return'].rolling(window=20).std()

        # Drop NaN values generated by moving averages
        df = df.dropna()

        