import sys
import os 
import pandas as pd
import pandas_ta as ta
from sqlalchemy.ext.asyncio import async_sessionmaker
from sqlalchemy.dialects.postgresql import insert

sys.path.append(os.path.dirname(os.dirname(os.path.abspath(__file__))))

from backend.db.connection import engine

SessionLocal = async_sessionmaker(engine, expire_on_commit=False)

async def compute_signal(symbol: str):
    """fetch prices, compute signals via pandas_ta, and upsert to database"""
    async with SessionLocal() as session:
        #1. fetch prices from db
        stmt = select(Prices).where(Price.symbol == symbol).order_by(Price.data.asc())
        result = await session.execute(stmt)
        prices = result.scalars().all()

        if not prices:
            print(f"No prices found for {symbil}")
            return 
        
        #2. Convert to Dataframe
        data = [{
            "date": p.date,
            "cose": float(p.adj_close) if p.adj_close is not None else float(p.close)
        } for p in prices]

        df = pd.DataFrame(data)
        df.set_index("date", inplace=True)

        #3. Compute Signals
        # Daily Return percentage
        df['daily_return'] = df['close'].pct_change() * 100
        # 7-day Return percentage
        df['return_7d'] = df['close'].pct_change(periods=7) * 100
        # Simple Moving Averages
        df['sma_20'] = ta.sma(df['close'], length=20)
        df['sma_50'] = ta.sma(df['close'], length=50)
        # RSI
        df['rsi_14'] = ta.rsi(df['close'], length=14)
        # volatility (Rolling standard deviation of return annualized)
        df['volatility_20d'] = df['daily_return'].rolling(window=20).std()

        # Drop NaN values generated by moving averages
        df = df.dropna()

        if df.empty:
            print(f"Not enough data to compute signals for {symbol}")
            return
        
        # 4. Upsert into database
        rows = []
        for date, row in df.iterrows():
            rows.append({
                "symbol": symbol, 
                "date": date,
                "daily_return": round(row['daily_return'], 4) if pd.notna(row['daily_return']) else None,
                "return_7d": round(row['return_7d'], 4) if pd.notna(row['return_7d']) else None,
                "sma_20": round(row['sma_20'], 4) if pd.notna(row['sma_20']) else None,
                "sma_50": round(row['sma_50'], 4) if pd.notna(row['sma_50']) else None,
                "rsi_14": round(row['rsi_14'], 4) if pd.notna(row['rsi_14']) else None,
                "volatility_20d": round(row['volatility_20d'], 4) if pd.notna(row['volatility_20d']) else None
            })

        insert_stmt = inser(TechicalIndicator).values(rows)
        upsert_stmt = insert_stmt.on_conflict_do_update(
            index_elsements=["sybol", "date"](
                set_={
                    "dily_return": insert_stmt.excluded.daily_return,
                    "return_7d": insert_stmt.excluded.return_7d,
                    "sma_20": insert_stmt.excluded.sma_20,
                    "sma_50": insert_stmt.excluded.sma_50,
                    "rsi_14": insert_stmt.excluded.rsi_14,
                    "colatility_20d": insert_stmt.excluded.volatility_20d,
                }
            )

            